### ISSUE TITLE
Bug in the wordlist generator

### ISSUE THREAD

**Issue by shelld3v** [maurosoria/dirsearch#304]
Hi,

When I ran dirsearch with the -e flag which for extensions, I received this output:

```python
Extensions:  | HTTP method: GET | Suffixes: html, htm, php, jsp, asp, js, json ...
```
It showed that there is no extension and there are several suffixes. The special thing here is that my wordlist itself was 8132 endpoints, then after rendered with several extensions, it supposed to be around 10000 endpoints and 10000 requests. But from the output:

```python
Wordlist size: 8052 | Request count: 8052 (+recursive)
```

Why is this happening, is it a bug? Can you explain this? My wordlist is something like this:

```
admin
index.%EXT%
login
api/
server.php
```
This is making me feel regret for updating dirsearch, it looked like using dirsearch v3.0.8 maybe better! Before everything gets fixed, I will use `ffuf` for sure 👌

**Comment by shelld3v** [comment]
Actually I just understood why it printed the extensions in the Suffixes tab, created a pull request to fix that bug: https://github.com/maurosoria/dirsearch/pull/305. But I still don't know what just happened with my wordlist size

**Comment by cybertix** [comment]
I am having the same issue. If i use -e html,php the output comes with suffixes:html,php and there is nothing in extension and no affect on wordlist size. 
`Extensions:  | HTTP method: GET | Suffixes: html,php, `
And when i use the option --suff=html,php -e json then the output is :
`Extensions: html,php  | HTTP method: GET | Suffixes: json `

**Comment by shelld3v** [comment]
@cybertix I have fixed that bug and submitted a pull request for it. But it will need to be applied by the author @maurosoria. Let's wait

**Comment by maurosoria** [comment]
this is resolved, right?

**Comment by shelld3v** [comment]
Let I check again 👌

**Comment by shelld3v** [comment]
No, this hasn't been fixed yet: 

```python
E:\Users\KPS\dirsearch>dirsearch.py -u https://example.com -e php,html

 _|. _ _  _  _  _ _|_    v0.3.9
(_||| _) (/_(_|| (_| )

Extensions: php, html | HTTP method: GET | Threads: 12 | Wordlist size: 8721 |
```

```python

 _|. _ _  _  _  _ _|_    v0.3.9
(_||| _) (/_(_|| (_| )

Extensions: php, html, txt, json, htm, xhtml, js | HTTP method: GET | Threads: 12 | Wordlist size: 8721 |
```

The second time I added more extensions but the wordlist size is still the same 🤨

**Comment by cybertix** [comment]
yes. The wordlist size remains constant regardless of number of extensions added.
So not fixed yet

**Comment by shelld3v** [comment]
This is a really BIG BIG BIG problem

**Comment by shelld3v** [comment]
I saw that the problem here is that dirsearch only processed the first extension:

```
127.0.0.1 - - [10/Sep/2020 11:22:49] "GET /php HTTP/1.1" 429 -
127.0.0.1 - - [10/Sep/2020 11:22:49] "GET /php.bak HTTP/1.1" 429 -
127.0.0.1 - - [10/Sep/2020 11:22:49] "GET /php.php HTTP/1.1" 429 -
127.0.0.1 - - [10/Sep/2020 11:22:49] "GET /php.tar HTTP/1.1" 429 -
127.0.0.1 - - [10/Sep/2020 11:22:49] "GET /php.txt HTTP/1.1" 429 -
127.0.0.1 - - [10/Sep/2020 11:22:49] "GET /php.zip HTTP/1.1" 429 -
```

Everything worked fine with the `-f` flag:
```python
dirsearch.py -u http://localhost:4444 -e php,html,txt,json,htm,xhtml,js -f

 _|. _ _  _  _  _ _|_    v0.3.9
(_||| _) (/_(_|| (_| )

Extensions: php, html, txt, json, htm, xhtml, js | HTTP method: GET | Threads: 12 | Wordlist size: 67046 |

Error Log: E:\Users\KPS\dirsearch\logs\errors-20-09-10_11-27-06.log
```

That means the problem must be in this code:

```python
                if '%ext%' in line.lower():
                    for extension in self._extensions:
                        if self._noDotExtensions:
                            line = reextdot.sub(extension, line)

                        line = reext.sub(extension, line)

                        quote = self.quote(line)
                        result.append(quote)
```

I am still investigating
