### ISSUE TITLE
Is there a way to automatically add redirects to the recursive queue?

### ISSUE THREAD

**Issue by f00d4w0rm4** [maurosoria/dirsearch#759]
When I used the default wordlist, it did not add gallery/ to the queue, but when I used a custom wordlist it did?  There was nothing in the error log.  I set recursive to true in default.conf.

```
$ dirsearch.py -u 192.168.87.91

[07:57:50] 301 -  316B  - /gallery  ->  http://192.168.87.91/gallery/
[07:57:51] 200 -  228B  - /index.php
[07:57:51] 301 -  319B  - /javascript  ->  http://192.168.87.91/javascript/
[07:57:52] 200 -    0B  - /lang.php

$ dirsearch.py -u 192.168.87.91 -w /usr/share/wordlists/dirbuster/directory-list-2.3-medium.txt -f

[08:00:18] 301 -  316B  - /gallery  ->  http://192.168.87.91/gallery/
[08:00:18] 200 -    1KB - /gallery/     (Added to queue)
[08:00:39] 301 -  319B  - /javascript  ->  http://192.168.87.91/javascript/
[08:00:39] 403 -  278B  - /javascript/     (Added to queue)
```

**Comment by shelld3v** [comment]
Hey, can you try: `dirsearch.py -u http://192.168.87.91 -w /usr/share/wordlists/dirbuster/directory-list-2.3-medium.txt -f`?

**Comment by f00d4w0rm4** [comment]
Is that different from what I did originally?

**Comment by Lucifer733** [comment]
Keep it you doing right

**Comment by shelld3v** [comment]
> Is that different from what I did originally?
> 
> Again, custom wordlists work, I'm trying to get it to work with the default wordlist.

Sorry for the late reply, the difference can be read in the [doc](https://github.com/maurosoria/dirsearch#about-wordlists)

**Comment by shelld3v** [comment]
I was unable to reproduce your problem in my local machine:

```
$ python3 dirsearch.py -u http://testphp.vulnweb.com/ -t 10 --remove-extensions
...
[11:38:08] Starting:
[11:38:09] 400 -  157B  - /%2e%2e//google
[11:38:09] 200 -    5KB - /.
[11:38:21] 301 -  169B  - /.idea  ->  http://testphp.vulnweb.com/.idea/     (Added to queue)
[11:38:21] 200 -  951B  - /.idea/
[11:38:41] 200 -  595B  - /CVS/     (Added to queue)
[11:38:41] 200 -    1B  - /CVS/Entries
[11:38:41] 200 -    1B  - /CVS/Root
[11:38:42] 301 -  169B  - /Connections  ->  http://testphp.vulnweb.com/Connections/     (Added to queue)
[11:38:55] 200 -  400B  - /_mmServerScripts/     (Added to queue)
[11:39:00] 301 -  169B  - /admin  ->  http://testphp.vulnweb.com/admin/     (Added to queue)
[11:39:01] 200 -  262B  - /admin/
[11:39:01] 200 -  262B  - /admin/?/login
[11:39:27] 403 -  276B  - /cgi-bin
[11:39:27] 403 -  276B  - /cgi-bin/     (Added to queue)
[11:39:50] 301 -  169B  - /images  ->  http://testphp.vulnweb.com/images/     (Added to queue)
[11:39:50] 200 -  377B  - /images/
[11:40:14] 301 -  169B  - /pictures  ->  http://testphp.vulnweb.com/pictures/     (Added to queue)
[11:40:23] 301 -  169B  - /secured  ->  http://testphp.vulnweb.com/secured/     (Added to queue)
[11:40:47] Starting: .idea/
...
```

**Comment by f00d4w0rm4** [comment]
I just looked at my notes from boxes I completed after that and it looks like it's working just fine.  Sorry I should have checked for this earlier.  I know I ran -t 100 so maybe that's what the issue was, however the error log was empty.  I'll just chalk this up to a one off.  Thanks for your reply!  

In case you still want it:
```
dirsearch v0.4.1

# If you want to edit dirsearch default configurations, you can
# edit values in this file. Everything after `#` is a comment
# and won't be applied

[mandatory]
default-extensions = php,html,txt,bak,old
force-extensions = False
# exclude-extensions = old,log

[general]
threads = 30
recursive = True
recursion-depth = 0
exclude-subdirs = %%ff/
random-user-agents = False
save-logs-home = False
skip-on-429 = False
full-url = False
quiet-mode = False
color = True
# include-status = 200,301
# exclude-status = 500,502
# exclude-sizes = 0b,123gb
# exclude-texts = "Not found"
# exclude-regexps = 403 [a-z]{1,25}
# calibration-path = InvalidPath123

[reports]
autosave-report = True
autosave-report-format = txt
## Support: txt, simple, json, xml, md, csv

[dictionary]
lowercase = False
uppercase = False
capitalization = False
# prefixes = .,admin
# suffixes = ~,.bak
# wordlist = db/dicc.txt

[request]
httpmethod = get
## Lowercase only
follow-redirects = False
# headers-file = headers.txt
# user-agent = MyUserAgent
# cookie = SESSIONID=123

[connection]
timeout = 10
delay = 0
scheme = http
max-retries = 3
request-by-hostname = False
exit-on-error = False
debug = False
# proxy = localhost:8080
# proxy-list = proxies.txt
# replay-proxy = localhost:8000
```

**Comment by shelld3v** [comment]
Hi, thanks for your response, but I believe 100 threads is not the root cause. Btw, if it was fixed, then you can close this

**Comment by f00d4w0rm4** [comment]
I thought it was just a fluke because it was working in the past few boxes I looked at but I'm doing one right now and came across the same issue.  Do you know why images was added to the queue but moodle wasn't?   

```
[09:04:51] 301 -  313B  - http://10.10.10.153/images  ->  http://10.10.10.153/images/
[09:04:51] 200 -   15KB - http://10.10.10.153/images/     (Added to queue)
[09:04:54] 301 -  313B  - http://10.10.10.153/moodle  ->  http://10.10.10.153/moodle/
[09:04:57] 403 -  297B  - http://10.10.10.153/phpmyadmin
[09:04:57] 403 -  298B  - http://10.10.10.153/phpmyadmin/     (Added to queue)
```

I noticed that in your reproduction, "(Added to queue)" is directly after the 301 redirect line, whereas mine are on the next line.  I tested --remove-extensions thinking my output would look similar to yours but it was still exactly the same as above.

I'm pretty sure the only thing I changed in default.conf was the extensions and recursive=true.  Should I also change "exclude-subdirs = %%ff/"?  I read through the docs and googled it but I'm not sure what %%ff/ means.

Please let me know if there's any other info you need from me.  This is definitely user error on my part so I appreciate you trying to help me out.

**Comment by f00d4w0rm4** [comment]
I just looked in the db/dicc.txt wordlist and I see now that there are two different lines for images and images/.

I added / to the extension list and that solved the issue!

**Comment by f00d4w0rm4** [comment]
Sorry, I spoke too soon...it looks like double // get added to the queue so the same subdirs are returned along with some errors.
```
[12:44:50] 200 -    8KB - http://10.10.10.153//     (Added to queue)
[12:45:05] 301 -  310B  - http://10.10.10.153/css  ->  http://10.10.10.153/css/
[12:47:22] 301 -  310B  - http://10.10.10.153//css  ->  http://10.10.10.153/css/
...
23.68% - Job: 2/7 - Last request to: TechnologySamples/PageReturner/Exception in thread Thread-49:
23.71% - Job: 2/7 - Last request to: TechnologySamples/SimpleJSP/Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
23.75% - Job: 2/7 - Last request to: TechnologySamples/SimpleJSP    self._target(*self._args, **self._kwargs)
  File "/opt/dirsearch/lib/core/fuzzer.py", line 173, in thread_proc
23.76% - Job: 2/7 - Last request to: TechnologySamples/Subscription/    status, response = self.scan(path)
23.77% - Job: 2/7 - Last request to: TechnologySamples/SimpleServlet/  File "/opt/dirsearch/lib/core/fuzzer.py", line 143, in scan
    response = self.requester.request(path)
  File "/opt/dirsearch/lib/connection/requester.py", line 168, in request
23.78% - Job: 2/7 - Last request to: TechnologySamples/Subscriptionservlet    response = self.session.request(
  File "/opt/dirsearch/thirdparty/requests/sessions.py", line 542, in request
24.01% - Job: 2/7 - Last request to: UserFiles    resp = self.send(prep, **send_kwargs)
23.86% - Job: 2/7 - Last request to: Trace.axd  File "/opt/dirsearch/thirdparty/requests/sessions.py", line 655, in send
23.90% - Job: 2/7 - Last request to: UPGRADE    r = adapter.send(request, **kwargs)
  File "/opt/dirsearch/thirdparty/requests/adapters.py", line 439, in send
23.93% - Job: 2/7 - Last request to: UpgradeLog.XML    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 627, in urlopen
23.95% - Job: 2/7 - Last request to: UserFile    parsed_url = parse_url(url)
23.97% - Job: 2/7 - Last request to: Upload  File "/usr/lib/python3/dist-packages/urllib3/util/url.py", line 392, in parse_url
    return six.raise_from(LocationParseError(source_url), None)
  File "<string>", line 3, in raise_from
23.99% - Job: 2/7 - Last request to: UserLogin/urllib3.exceptions.LocationParseError: Failed to parse: //Trace.axd::$DATA
```

**Comment by shelld3v** [comment]
@f00d4w0rm4 Are you using the latest version of dirsearch?

**Comment by f00d4w0rm4** [comment]
Yeah, 0.4.1 right? For now I'm doing -f --exclude-status=403 to get the results I'm looking for but I feel like there might be a better way to do it. I still don't get "added to queue" on the same line as the 301s.

**Comment by shelld3v** [comment]
> Yeah, 0.4.1 right? For now I'm doing -f --exclude-status=403 to get the results I'm looking for but I feel like there might be a better way to do it. I still don't get "added to queue" on the same line as the 301s.

It's so weird that from your last comment, I saw an old bug that was fixed a long time ago. Can you re-git the project?

**Comment by f00d4w0rm4** [comment]
Sorry for the late response, I tried that but the problem persists.  I'm running it as a user with zsh and tried to su to root but that didn't work either.  It's not a huge deal though as I can still get the desired behavior to work with the default wordlist by using -f --exclude-status=403, but I'd be happy to try anything else you recommend.

**Comment by shelld3v** [comment]
> Sorry for the late response, I tried that but the problem persists. I'm running it as a user with zsh and tried to su to root but that didn't work either. It's not a huge deal though as I can still get the desired behavior to work with the default wordlist by using -f --exclude-status=403, but I'd be happy to try anything else you recommend.

What is your wordlist? Default one?

**Comment by f00d4w0rm4** [comment]
When you don't use -w isn't the default wordlist db/dicc.txt?

**Comment by shelld3v** [comment]
Hey, I just realized that the current latest version is 0.4.2, not 0.4.1, please update it

**Comment by shelld3v** [comment]
Please close this

**Comment by shelld3v** [comment]
> Hey, I just realized that the current latest version is 0.4.2, not 0.4.1, please update it

Oh, my bad, the latest version is 0.4.1! Sorry so much, but can you git clone dirsearch again?

**Comment by shelld3v** [comment]
Hi @f00d4w0rm4, can you remove the current dirsearch and then try gitting it again? I believe it can fix your issue

**Comment by shelld3v** [comment]
> Sorry for the late response, I tried that but the problem persists. I'm running it as a user with zsh and tried to su to root but that didn't work either. It's not a huge deal though as I can still get the desired behavior to work with the default wordlist by using -f --exclude-status=403, but I'd be happy to try anything else you recommend.

Can you give me the error traceback?

**Comment by shelld3v** [comment]
Hi, how are you doing with dirsearch? Have you fixed the issue yet?

**Comment by shelld3v** [comment]
Please update your dirsearch with `git clone https://github.com/maurosoria/dirsearch`, and close this when fixed

**Comment by shelld3v** [comment]
I am closing this because there isn't any update from you. Feel free to comment if the issue hasn't been solved
