### ISSUE TITLE
Many duplicate records in report files

### ISSUE THREAD

**Issue by BlackDiverX** [maurosoria/dirsearch#766]
When use flag `-l` in report files many duplicates (for big sites in gigabytes):
Example command, for bug output:

./dirsearch.py -l /domains.txt -t 10 -w /opt/wordlist.txt -i 200,301,302

Example reports catalog file output:

Example file: dirsearch/reports/BATCH-<date-time>/domain

`Time: Mon Mar  1 01:13:42 2021

200     4KB  https://domain:443/!.htpasswd
Time: Mon Mar  1 01:13:42 2021

200     4KB  https://domain:443/!.htpasswd
200     4KB  https://domain:443/.7z
Time: Mon Mar  1 01:13:42 2021

200     4KB  https://domain:443/!.htpasswd
200     4KB  https://domain:443/.7z
200     4KB  https://domain:443/!.htaccess
Time: Mon Mar  1 01:13:42 2021

200     4KB  https://domain:443/!.htpasswd
200     4KB  https://domain:443/.7z
200     4KB  https://domain:443/!.htaccess
200     4KB  https://domain:443/.addressbook
Time: Mon Mar  1 01:13:42 2021

200     4KB  https://domain:443/!.htpasswd
200     4KB  https://domain:443/.7z
200     4KB  https://domain:443/!.htaccess
200     4KB  https://domain:443/.addressbook
200     4KB  https://domain:443/.adm
Time: Mon Mar  1 01:13:42 2021

200     4KB  https://domain:443/!.htpasswd
200     4KB  https://domain:443/.7z
200     4KB  https://domain:443/!.htaccess
200     4KB  https://domain:443/.addressbook
200     4KB  https://domain:443/.adm
200     4KB  https://domain:443/.access
Time: Mon Mar  1 01:13:42 2021

200     4KB  https://domain:443/!.htpasswd
200     4KB  https://domain:443/.7z
200     4KB  https://domain:443/!.htaccess
200     4KB  https://domain:443/.addressbook
200     4KB  https://domain:443/.adm
`
...... and more gigabytes similar output.
P.S. is use -u flag - all ok, reports not duplicates.

**Comment by shelld3v** [comment]
Hi, this has been fixed for a while, please update your dirsearch

**Comment by BlackDiverX** [comment]
i'm use latest version (`git clone https://github.com/maurosoria/dirsearch`)
Bug remained after remove folder with dirsearch and new clone repo.

**Comment by shelld3v** [comment]
I confirmed this bug

**Comment by bootyhunt3r** [comment]
@BlackDiverX , can you tell me how to remove these duplicates ? I am also having this issue , the output file size is going into gigabytes which is pretty useless.

**Comment by shelld3v** [comment]
Hey @bootyhunt3r, this is a bug, and I submitted a PR to fix this. But, I contacted @maurosoria and it looks like he is having a lot of problems to resolve and can't merge PRs now. So please be patient @bootyhunt3r

**Comment by BlackDiverX** [comment]
> @BlackDiverX , can you tell me how to remove these duplicates ? I am also having this issue , the output file size is going into gigabytes which is pretty useless.

i'm use:
`cat domains.txt | while read in; do ./dirsearch -u $in -w wordlist.txt ; done`

**Comment by bootyhunt3r** [comment]
@BlackDiverX  , can you also tell me the whole dirsearch command please ?  It would be really helpful , thanks.
