### ISSUE TITLE
Option exit-on-error=False with https no work

### ISSUE THREAD

**Issue by p1ne4pple** [maurosoria/dirsearch#836]
### What is the current behavior?

What actually happens?
Cannot connect to: www.xx.com:443

### What is the expected behavior?

What it should be instead?
skip this target

### Any additional information?

OS, python version, screenshots, dirsearch command, console output, ...?
```
Traceback (most recent call last):
  File "/root/dirsearch/lib/controller/controller.py", line 203, in __init__
    self.requester.request("")
  File "/root/dirsearch/lib/connection/requester.py", line 217, in request
    raise RequestException({"message": error})
lib.connection.request_exception.RequestException: {'message': 'Cannot connect to: www.xx.com:443'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/dirsearch/lib/controller/controller.py", line 208, in __init__
    raise SkipTargetInterrupt
lib.controller.controller.SkipTargetInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dirsearch.py", line 47, in <module>
    main = Program()
  File "dirsearch.py", line 43, in __init__
    self.controller = Controller(self.script_path, self.arguments, self.output)
  File "/root/dirsearch/lib/controller/controller.py", line 248, in __init__
    self.report.completed = True
AttributeError: 'NoneType' object has no attribute 'completed'
```

#### Checker:
 - [ ✔ ] I tested in the latest version of dirsearch

**Comment by shelld3v** [comment]
Hi, this has been fixed in the latest commit

**Comment by yangyang-zhang** [comment]
This problem still exists in version 0.4.2

sudo dirsearch -l domains.txt -w words.txt 

```
Traceback (most recent call last):
  File "/Library/Python/3.8/site-packages/dirsearch/lib/controller/controller.py", line 201, in __init__
    self.requester.request("")
  File "/Library/Python/3.8/site-packages/dirsearch/lib/connection/requester.py", line 234, in request
    raise RequestException({"message": error})
lib.connection.request_exception.RequestException: {'message': 'Cannot connect to: xx.com:80'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Python/3.8/site-packages/dirsearch/lib/controller/controller.py", line 208, in __init__
    raise SkipTargetInterrupt
lib.controller.controller.SkipTargetInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/dirsearch", line 10, in <module>
    sys.exit(Program())
  File "/Library/Python/3.8/site-packages/dirsearch/dirsearch.py", line 43, in __init__
    self.controller = Controller(self.script_path, self.arguments, self.output)
  File "/Library/Python/3.8/site-packages/dirsearch/lib/controller/controller.py", line 247, in __init__
    self.report.completed = True
AttributeError: 'NoneType' object has no attribute 'completed'
```

**Comment by shelld3v** [comment]
@yangyang-zhang Please install with git for latest commits: `git clone https://github.com/maurosoria/dirsearch`
